### ISSUE TITLE
Error when populating segment: Error in protected function: Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by APBatten** [Robin-Lord/GA4-js#1]
Awesome idea, and thank you for creating this! 

I was testing on our accounts, and I'm running into the attached error repeatedly when the script attempts to populate the segment on the first report, and the execution stops.

![image](https://user-images.githubusercontent.com/83288718/189903771-700a121b-1951-400b-9a69-52f344be9fc4.png)

**Comment by Robin-Lord** [comment]
Hi there, I've just rerun the code and I can't replicate the issue, how far does it get exactly?

**Comment by Robin-Lord** [comment]
Hi, because I can't replicate this issue I'm going to close this. Feel free to come back if you have more info on the issue you're facing in future.

Thanks
