### ISSUE TITLE
Stops when it has created first report without segments

### ISSUE THREAD

**Issue by Nordicbranch** [Robin-Lord/GA4-js#2]
<img width="1653" alt="Skärmavbild 2022-09-20 kl  16 12 51" src="https://user-images.githubusercontent.com/114002468/191282642-28a88dde-9e61-4862-a91f-f85813f512ac.png">

**Comment by Robin-Lord** [comment]
Thanks for this, looks like some css selectors changed - have updated the code to match the new selectors and it works in testing.
